# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   builder: html
   configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - sphinx-github-changelog
        - sphinx-autodoc-typehints
        - sphinx-rtd-theme
        - myst-nb