name: Small Benchmarks

on: 
  push:
    paths:
      - 'pysipfenn/descriptorDefinitions/**'
      - '.github/workflows/benchmarks.yaml'
  workflow_dispatch:

jobs:
  benchmark:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install wheel flask
          python -m pip install -e .

      - name: Benchmark KS2022
        run: python -c "from pysipfenn.descriptorDefinitions import KS2022; KS2022.profile(test='JVASP-10001', nRuns=100); KS2022.profile(test='diluteNiAlloy', nRuns=100)"

      - name: Benchmark Ward2017
        run: python -c "from pysipfenn.descriptorDefinitions import Ward2017; Ward2017.profile(test='JVASP-10001', nRuns=100); Ward2017.profile(test='diluteNiAlloy', nRuns=100)"

      - name: Benchmark KS2022 dilute featurizer
        run: python -c "from pysipfenn.descriptorDefinitions import KS2022_dilute; KS2022_dilute.profile(test='diluteNiAlloy', nRuns=250)"

