name: Core Functions

on: [push, pull_request, release]

jobs:
  coreTest:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install wheel flask pytest pytest-cov
          python -m pip install -e .
      - name: Test with pytest
        run: |
          pytest --cov=pysipfenn --cov-report=xml
