name: Partial Test

on: [push]

jobs:
  coverage-python310:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flask pytest pytest-cov
          python -m pip install -e .
      - name: Test with pytest
        run: |
          pytest --cov=pyqalloy --cov-report=xml
